### ISSUE TITLE
missing nsfw_200.txt

### ISSUE THREAD

**Issue by bosbrand** [Yuchen413/text2image_safety#3]
I use the line provided in the readme, but nothing really happens. Only thing it says is that it's missing a nsfw_200 text file. 
Can you provide a better description of how to use this?  Where do you put in the target prompt, where do you find the adversarial prompt? I want to make better negative prompts for SD, because there's often too much nudity, too short hemlines etc., so when I read about your research I thought maybe I can use it to improve the safety.

**Comment by Yuchen413** [comment]
Please send me an email to request access to the NSFW200 since it contains disturbing content that is inappropriate to be public, thanks for your understanding!

**Comment by yo31400** [comment]
Hello, What email address can we contact you on to have access to this dataset?

**Comment by Yuchen413** [comment]
***@***.***

**Comment by garugann** [comment]
Sorry, I also want to access this dataset but I can't find the email address. How should I contact them .

**Comment by cs-w0r1d** [comment]
Hello, What email address can we contact you on to have access to this dataset?
