### ISSUE TITLE
I have Ubuntu 18.04 with a 3090 NVIDIA and am having problems getting this to run 

### ISSUE THREAD

**Issue by dexterinbk** [Yuchen413/text2image_safety#5]
Is there a required python version to get this to run correctly?  The build versions specified seem to give various error messages due to an incompatibility between keras and tensorflow versions.  Any help would be much appreciated!

**Comment by dexterinbk** [comment]
finally got the dependencies to match

**Comment by rain305f** [comment]
How do you to solve the dismatch problems among the dependencies
