### ISSUE TITLE
Cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental'

### ISSUE THREAD

**Issue by rain305f** [Yuchen413/text2image_safety#6]
I have Red Hat 4.8.5-44.0.3 with a a100 NVIDIA and am having problems getting this to run.
How to fix it?
Thanks
![image](https://github.com/Yuchen413/text2image_safety/assets/128030543/32b60773-b0d4-43e2-9d9a-c89da493cad6)

**Comment by rain305f** [comment]
I address this problem by "pip install keras==2.8.0rc0" ,

**Comment by rain305f** [comment]
Can you help me to address this problem? Thanks！！！ @Yuchen413

**Comment by rain305f** [comment]
pip install keras==2.8.0rc1 may be address this problem

**Comment by Ezuharad** [comment]
After I did this I had to repeat the steps in Issue #7 for anyone else trying to replicate the work.
